apiVersion: v1
kind: ReplicationController
metadata:
  name: webapp-rc
spec:
  replicas: 1
  selector:
    app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: hello
        image: registry.ng.bluemix.net/ishan/nginx-server
        ports:
        - containerPort: 80
        env:
          - name: SOURCE_IP
           #replace the value IP
            value: xx.xx.xx.xx
---
apiVersion: v1
kind: Service
metadata:
  name: webapp-svc
spec:
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30056
    protocol: TCP
    name: http
  selector:
    app: webapp
  type : NodePort
