apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: microservice-schedule-sample
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: schedule-deployment
    spec:
      containers:
      - name: microservice-schedule
        image: docker.io/ishangulhane/microservice-schedule
#       env:
#       - name: EXTERNAL_IP_ADDR
#         valueFrom:
#           configMapKeyRef:
#             name: ipaddr-config
#             key: EXTERNAL_IP_ADDR
        ports:
          - containerPort: 9080
        volumeMounts:
        - name: keystore
          mountPath: /etc/wlp/config/keystore
        - name: truststore
          mountPath: /etc/wlp/config/truststore
        - name: liberty-config
          mountPath: /config/configDropins
      volumes:
       - name: keystore
         secret:
           secretName: wlp-keystore
       - name: truststore
         secret:
           secretName: wlp-truststore
       - name: liberty-config
         configMap:
           name: liberty-config
           items:
             - key: keystore.xml
               path: defaults/keystore.xml
             - key: logging.xml
               path: defaults/logging.xml
---
apiVersion: v1
kind: Service
metadata:
  name: schedule-service
  namespace: default
spec:
  ports:
    - port: 9080
      targetPort: 9080
      nodePort: 30054
  selector:
    name: schedule-deployment
  type: NodePort
