apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: microservice-webapp-sample
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: webapp-deployment
    spec:
      containers:
      - name: microservice-webapp
        image: registry.ng.bluemix.net/<namespace>/web-application
        ports:
          - containerPort: 9080
        imagePullPolicy: IfNotPresent
---
apiVersion: v1
kind: Service
metadata:
  name: webapp-service
  namespace: default
spec:
  ports:
    - port: 9080
      targetPort: 9080
      nodePort: 30051
  selector:
    name: webapp-deployment
  type: NodePort
