apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx-server
    spec:
      containers:
      - name: hello
        image: registry.ng.bluemix.net/ishan/nginx-server
        ports:
        - containerPort: 80
        env:
          - name: SOURCE_IP
            value: xx.xx.xx.xx
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
spec:
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30056
    protocol: TCP
    name: http
  selector:
    app: nginx
  type : NodePort
